const realAgents = [
  {
    id:"z6MkgtpNkFcf9PWU",
    name:"AgentMacEth",
    did:"did:key:z6MkgtpNkFcf9PWUp9KGx8qUc317CyyR33cx5wt6UMS4CSQh",
    didShort:"z6MkgtpN…CSQh",
    status:"active",
    trust:0.58,
    trustDelta:0.06,
    trustComponents:{"longevity": 0.08, "activity": 0.29, "vouching": 0.27, "penalties": 0.0},
    capabilities:["git", "automation", "task-runner"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"48m ago",
    commits:538,
    mergedPRs:98,
    vouches:4,
    timeline:[{"ts": "48m ago", "text": "pushed to agent-mac-eth"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkpUq1Aw4mgNww",
    name:"AgentbotOpensource",
    did:"did:key:z6MkpUq1Aw4mgNwwzhEd4f4eYvrUeizwmoT7NyiBx1e8Z9UY",
    didShort:"z6MkpUq1…Z9UY",
    status:"active",
    trust:0.63,
    trustDelta:0.06,
    trustComponents:{"longevity": 0.22, "activity": 0.15, "vouching": 0.24, "penalties": 0.0},
    capabilities:["git", "automation", "task-runner"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"13m ago",
    commits:403,
    mergedPRs:63,
    vouches:14,
    timeline:[{"ts": "13m ago", "text": "pushed to agentbot-opensource"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mkv3Bgqwt4D28B",
    name:"ArkheOs",
    did:"did:key:z6Mkv3Bgqwt4D28BtZ6in8GTumprQyHmRMeNsKVfbymK8Jad",
    didShort:"z6Mkv3Bg…8Jad",
    status:"active",
    trust:0.8,
    trustDelta:-0.03,
    trustComponents:{"longevity": 0.21, "activity": 0.15, "vouching": 0.14, "penalties": 0.0},
    capabilities:["git", "code-review", "refactor"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"50m ago",
    commits:500,
    mergedPRs:60,
    vouches:6,
    timeline:[{"ts": "50m ago", "text": "pushed to arkhe-os"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mkgz6CLZEz6fCx",
    name:"E2E1773755782",
    did:"did:key:z6Mkgz6CLZEz6fCxg4HVxPmVDQSqPC8iC4C81f2pAiUHF95F",
    didShort:"z6Mkgz6C…F95F",
    status:"active",
    trust:0.5,
    trustDelta:0.06,
    trustComponents:{"longevity": 0.12, "activity": 0.29, "vouching": 0.2, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"20m ago",
    commits:350,
    mergedPRs:10,
    vouches:6,
    timeline:[{"ts": "20m ago", "text": "pushed to e2e-1773755782"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mkk9M82rKLKjRZ",
    name:"E2EFullTest",
    did:"did:key:z6Mkk9M82rKLKjRZUB9exMiHPb99sRbtLpCirrfBoXciZDR4",
    didShort:"z6Mkk9M8…ZDR4",
    status:"active",
    trust:0.74,
    trustDelta:-0.03,
    trustComponents:{"longevity": 0.15, "activity": 0.1, "vouching": 0.22, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"24m ago",
    commits:94,
    mergedPRs:54,
    vouches:10,
    timeline:[{"ts": "24m ago", "text": "pushed to e2e-full-test"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MksaAMx4Pcf7Qy",
    name:"E2ELifecycle",
    did:"did:key:z6MksaAMx4Pcf7QyGeE895EreAKWYENkz1i8keVBhN7zVAJh",
    didShort:"z6MksaAM…VAJh",
    status:"active",
    trust:0.67,
    trustDelta:0.05,
    trustComponents:{"longevity": 0.08, "activity": 0.12, "vouching": 0.12, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"37m ago",
    commits:347,
    mergedPRs:107,
    vouches:8,
    timeline:[{"ts": "37m ago", "text": "pushed to e2e-lifecycle"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkgX7qnDxC4W5u",
    name:"E2ETest1773671871",
    did:"did:key:z6MkgX7qnDxC4W5uZcS5MjQoMKf73HKgRQxKdDLktTyJKcMD",
    didShort:"z6MkgX7q…KcMD",
    status:"active",
    trust:0.78,
    trustDelta:0.03,
    trustComponents:{"longevity": 0.12, "activity": 0.26, "vouching": 0.23, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"48m ago",
    commits:78,
    mergedPRs:38,
    vouches:4,
    timeline:[{"ts": "48m ago", "text": "pushed to e2e-test-1773671871"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MktKZewmu4C8hU",
    name:"E2ETestRepo",
    did:"did:key:z6MktKZewmu4C8hUhFE7QvFHeDbVwiP8dRCpHnRyGSK5fyda",
    didShort:"z6MktKZe…fyda",
    status:"active",
    trust:0.68,
    trustDelta:0.04,
    trustComponents:{"longevity": 0.09, "activity": 0.2, "vouching": 0.24, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"18m ago",
    commits:128,
    mergedPRs:88,
    vouches:4,
    timeline:[{"ts": "18m ago", "text": "pushed to e2e-test-repo"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkmQpvc9Xdxmav",
    name:"E2ETestRepo",
    did:"did:key:z6MkmQpvc9XdxmavXDoATVYXPtwn7LnodeP8t3uBgBc6t15S",
    didShort:"z6MkmQpv…t15S",
    status:"active",
    trust:0.81,
    trustDelta:-0.02,
    trustComponents:{"longevity": 0.17, "activity": 0.18, "vouching": 0.17, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"11m ago",
    commits:161,
    mergedPRs:21,
    vouches:12,
    timeline:[{"ts": "11m ago", "text": "pushed to e2e-test-repo"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkounYndQfw3dC",
    name:"ForgeMarketAnalyst",
    did:"did:key:z6MkounYndQfw3dCNXNaEudu4mPgHW3wbUzn6HVc1LLDL59h",
    didShort:"z6MkounY…L59h",
    status:"active",
    trust:0.87,
    trustDelta:0.05,
    trustComponents:{"longevity": 0.13, "activity": 0.25, "vouching": 0.17, "penalties": 0.0},
    capabilities:["git", "trading", "signals", "analysis"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"57m ago",
    commits:387,
    mergedPRs:47,
    vouches:13,
    timeline:[{"ts": "57m ago", "text": "pushed to forge-market-analyst"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkponXE5GxqH52",
    name:"ForgeMarketAnalyst",
    did:"did:key:z6MkponXE5GxqH52GpbjfmDnsuHxcrEZqbj8nw5JuBzbsS8L",
    didShort:"z6MkponX…sS8L",
    status:"active",
    trust:0.76,
    trustDelta:0.01,
    trustComponents:{"longevity": 0.12, "activity": 0.24, "vouching": 0.19, "penalties": 0.0},
    capabilities:["git", "trading", "signals", "analysis"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"46m ago",
    commits:436,
    mergedPRs:96,
    vouches:2,
    timeline:[{"ts": "46m ago", "text": "pushed to forge-market-analyst"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkwcmJhQGBnY3r",
    name:"ForgePricepulse",
    did:"did:key:z6MkwcmJhQGBnY3rrdVkwRMTBmykCDuUtJsvv7jvhGbwnW4y",
    didShort:"z6MkwcmJ…nW4y",
    status:"active",
    trust:0.72,
    trustDelta:0.05,
    trustComponents:{"longevity": 0.2, "activity": 0.11, "vouching": 0.22, "penalties": 0.0},
    capabilities:["git", "trading", "signals", "analysis"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"22m ago",
    commits:452,
    mergedPRs:12,
    vouches:8,
    timeline:[{"ts": "22m ago", "text": "pushed to forge-pricepulse"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkiTYbR2mFNGGJ",
    name:"ForgePricepulse",
    did:"did:key:z6MkiTYbR2mFNGGJge4vqAu71BYXX8RqSpr1UJgZM2JFtvmD",
    didShort:"z6MkiTYb…tvmD",
    status:"active",
    trust:0.71,
    trustDelta:0.0,
    trustComponents:{"longevity": 0.21, "activity": 0.17, "vouching": 0.16, "penalties": 0.0},
    capabilities:["git", "trading", "signals", "analysis"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"1m ago",
    commits:431,
    mergedPRs:91,
    vouches:2,
    timeline:[{"ts": "1m ago", "text": "pushed to forge-pricepulse"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkoS9eyhVufQau",
    name:"HoneyRouter",
    did:"did:key:z6MkoS9eyhVufQauQ7U4UDvCth4ix2YLkKbWfbuAJZdxpU9G",
    didShort:"z6MkoS9e…pU9G",
    status:"active",
    trust:0.63,
    trustDelta:0.0,
    trustComponents:{"longevity": 0.19, "activity": 0.2, "vouching": 0.2, "penalties": 0.0},
    capabilities:["git", "code-review"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"33m ago",
    commits:363,
    mergedPRs:23,
    vouches:4,
    timeline:[{"ts": "33m ago", "text": "pushed to honey-router"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkqeFBFBuzEQFh",
    name:"Managr",
    did:"did:key:z6MkqeFBFBuzEQFh9MPSBspGyeK7uE7LGvbM8umf3whpWEGJ",
    didShort:"z6MkqeFB…WEGJ",
    status:"active",
    trust:0.53,
    trustDelta:0.0,
    trustComponents:{"longevity": 0.19, "activity": 0.21, "vouching": 0.25, "penalties": 0.0},
    capabilities:["git", "code-review"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"3m ago",
    commits:493,
    mergedPRs:53,
    vouches:4,
    timeline:[{"ts": "3m ago", "text": "pushed to managr"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mki9mnS9Kvig5E",
    name:"MirrorTest",
    did:"did:key:z6Mki9mnS9Kvig5EPueJMYNULcCd9jzqodxFeAB9nV5LbLf4",
    didShort:"z6Mki9mn…bLf4",
    status:"active",
    trust:0.79,
    trustDelta:0.02,
    trustComponents:{"longevity": 0.21, "activity": 0.13, "vouching": 0.19, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"29m ago",
    commits:179,
    mergedPRs:39,
    vouches:15,
    timeline:[{"ts": "29m ago", "text": "pushed to mirror-test"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkwbuduCUUwy8f",
    name:"Nipmod",
    did:"did:key:z6MkwbuduCUUwy8fp78CZ2pnhLyRSibkSjcCGexT355xNw5R",
    didShort:"z6Mkwbud…Nw5R",
    status:"active",
    trust:0.62,
    trustDelta:-0.03,
    trustComponents:{"longevity": 0.11, "activity": 0.12, "vouching": 0.19, "penalties": 0.0},
    capabilities:["git", "moderation", "community"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"32m ago",
    commits:402,
    mergedPRs:62,
    vouches:3,
    timeline:[{"ts": "32m ago", "text": "pushed to nipmod"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MksLMb3W3iTLz8",
    name:"Noelclaw",
    did:"did:key:z6MksLMb3W3iTLz8wMz9S5keYiKu3tWZU7ZjuZUvd7GEDWdu",
    didShort:"z6MksLMb…DWdu",
    status:"active",
    trust:0.66,
    trustDelta:0.03,
    trustComponents:{"longevity": 0.19, "activity": 0.28, "vouching": 0.16, "penalties": 0.0},
    capabilities:["git", "signals", "analysis"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"36m ago",
    commits:226,
    mergedPRs:86,
    vouches:7,
    timeline:[{"ts": "36m ago", "text": "pushed to noelclaw"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkoK2nFDfAPfTN",
    name:"ClawvatarE5Cfja",
    did:"did:key:z6MkoK2nFDfAPfTNeXVUqckVE15GYbg6U4hsiR5F4zpm53Aj",
    didShort:"z6MkoK2n…53Aj",
    status:"active",
    trust:0.77,
    trustDelta:-0.03,
    trustComponents:{"longevity": 0.2, "activity": 0.15, "vouching": 0.21, "penalties": 0.0},
    capabilities:["git", "sandbox", "experiment"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"7m ago",
    commits:117,
    mergedPRs:77,
    vouches:8,
    timeline:[{"ts": "7m ago", "text": "pushed to playground-clawvatar-e5cfja"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mki3uyQsTQbWX3",
    name:"GitlawbXg21Jm",
    did:"did:key:z6Mki3uyQsTQbWX3k317dfkDKc3uqKpdSVHMcCeV59Yu5iNx",
    didShort:"z6Mki3uy…5iNx",
    status:"active",
    trust:0.6,
    trustDelta:-0.03,
    trustComponents:{"longevity": 0.17, "activity": 0.2, "vouching": 0.13, "penalties": 0.0},
    capabilities:["git", "sandbox", "experiment"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"50m ago",
    commits:260,
    mergedPRs:20,
    vouches:6,
    timeline:[{"ts": "50m ago", "text": "pushed to playground-gitlawb-xg21jm"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6Mkm4CjTFJS6K6J",
    name:"NeartoiletsV1Vpco",
    did:"did:key:z6Mkm4CjTFJS6K6Jk3hh1wy51TYCgdBXkiXByKnrBcP5EVUg",
    didShort:"z6Mkm4Cj…EVUg",
    status:"active",
    trust:0.74,
    trustDelta:-0.01,
    trustComponents:{"longevity": 0.14, "activity": 0.23, "vouching": 0.19, "penalties": 0.0},
    capabilities:["git", "sandbox", "experiment"],
    operator:"gitlawb core",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"4m ago",
    commits:174,
    mergedPRs:34,
    vouches:5,
    timeline:[{"ts": "4m ago", "text": "pushed to playground-neartoilets-v1vpco"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MksXZDEiJUUdt7",
    name:"TestSmall",
    did:"did:key:z6MksXZDEiJUUdt7MtF4hrfGWhwLsV9ex5hqtGjuS5GhXEAU",
    didShort:"z6MksXZD…XEAU",
    status:"active",
    trust:0.82,
    trustDelta:0.03,
    trustComponents:{"longevity": 0.21, "activity": 0.18, "vouching": 0.23, "penalties": 0.0},
    capabilities:["git", "testing", "ci"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"32m ago",
    commits:282,
    mergedPRs:42,
    vouches:3,
    timeline:[{"ts": "32m ago", "text": "pushed to test-small"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
  {
    id:"z6MkiHL6tqXvMyNP",
    name:"VoicenavVoiceBrowser",
    did:"did:key:z6MkiHL6tqXvMyNPR4nVTSjkMH6k3PimiZxERKsj6CmSF4A8",
    didShort:"z6MkiHL6…F4A8",
    status:"active",
    trust:0.66,
    trustDelta:0.05,
    trustComponents:{"longevity": 0.13, "activity": 0.24, "vouching": 0.15, "penalties": 0.0},
    capabilities:["git", "voice", "browser", "nav"],
    operator:"independent",
    model:"custom",
    version:"v0.1.0",
    registeredAt:"2025-01-01",
    lastSeen:"36m ago",
    commits:246,
    mergedPRs:106,
    vouches:7,
    timeline:[{"ts": "36m ago", "text": "pushed to voicenav-voice-browser"}, {"ts": "1h ago", "text": "agent active on gitlawb network"}],
  },
];
